#!/bin/bash -e
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/mariadb:latest}
VERSION=${VERSION-"latest"}

VERSION_COMMAND="mysqld --version"

CONTAINER_ARGS="-e MYSQL_ROOT_PASSWORD=ausnimbus -e MYSQL_DATABASE=test -e MYSQL_USER=test -e MYSQL_PASSWORD=test"

extra_tests() {

  info "Sleep for a bit while MariaDB boots up.."
  sleep 60

  info "Testing MySQL set"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'CREATE TABLE tbl (col1 VARCHAR(20), col2 VARCHAR(20))';"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'INSERT INTO tbl VALUES (\"foo1\", \"bar1\")';"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'INSERT INTO tbl VALUES (\"foo2\", \"bar2\")';"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'INSERT INTO tbl VALUES (\"foo3\", \"bar3\")';"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'SELECT * FROM tbl';"
  container_exec "mysql --host $(container_ip) -utest -ptest test -e 'DROP TABLE tbl';"

}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/component
