#!/bin/bash -e
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/mariadb:latest}
VERSION=${VERSION-"latest"}

VERSION_COMMAND="mysqld --version"

CONTAINER_ARGS="--user=root -e MYSQL_ROOT_PASSWORD=ausnimbus -e MYSQL_DATABASE=test -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e POD_NAMESPACE=ausnimbus"

extra_tests() {

  info "Sleep for a bit while MariaDB boots up.."
  sleep 60

  info "Testing MySQL set"
  container_exec "echo 'CREATE TABLE tbl (col1 VARCHAR(20), col2 VARCHAR(20));' | mysql --host $(container_ip) -utest -ptest test"

  info "Testing MySQL insert"
  container_exec "echo 'INSERT INTO tbl VALUES (\"foo1\", \"bar1\");' | mysql --host $(container_ip) -utest -ptest test"
  container_exec "echo 'INSERT INTO tbl VALUES (\"foo2\", \"bar2\");' | mysql --host $(container_ip) -utest -ptest test"
  container_exec "echo 'INSERT INTO tbl VALUES (\"foo3\", \"bar3\");' | mysql --host $(container_ip) -utest -ptest test"

  info "Testing MySQL select"
  container_exec "echo 'SELECT * FROM tbl;' | mysql --host $(container_ip) -utest -ptest test"

  info "Testing MySQL drop"
  container_exec "echo 'DROP TABLE tbl;' | mysql --host $(container_ip) -utest -ptest test"

}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/component
