#!/bin/bash
source cgroup-limits

export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}
export MYSQL_DATABASE=${MYSQL_DATABASE:-}
export MYSQL_USER=${MYSQL_USER:-}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-}

# Fall back to random root password
if [[ -z "$MYSQL_ROOT_PASSWORD" ]]; then
  export MYSQL_RANDOM_ROOT_PASSWORD="yes"
fi

export MYSQL_BINLOG_FORMAT=${MYSQL_BINLOG_FORMAT:-STATEMENT}
export MYSQL_LOWER_CASE_TABLE_NAMES=${MYSQL_LOWER_CASE_TABLE_NAMES:-0}
export MYSQL_FT_MIN_WORD_LEN=${MYSQL_FT_MIN_WORD_LEN:-4}
export MYSQL_FT_MAX_WORD_LEN=${MYSQL_FT_MAX_WORD_LEN:-20}
export MYSQL_AIO=${MYSQL_AIO:-1}
export MYSQL_MAX_ALLOWED_PACKET=${MYSQL_MAX_ALLOWED_PACKET:-200M}
export MYSQL_TABLE_OPEN_CACHE=${MYSQL_TABLE_OPEN_CACHE:-400}
export MYSQL_SORT_BUFFER_SIZE=${MYSQL_SORT_BUFFER_SIZE:-256K}

# Auto-tuning
if [ -z "${MEMORY_LIMIT_IN_BYTES:-}" ]; then
    key_buffer_size='32M'
    read_buffer_size='8M'
    innodb_buffer_pool_size='32M'
    innodb_log_file_size='8M'
    innodb_log_buffer_size='8M'
    max_connections='16'
else
    # memory section
    key_buffer_size=$(( $MEMORY_LIMIT * 9 / 100 ))M
    read_buffer_size=$(( $MEMORY_LIMIT * 5 / 100 ))M
    innodb_buffer_pool_size=$(( $MEMORY_LIMIT * 45 / 100 ))M
    innodb_log_file_size=$(( $MEMORY_LIMIT * 13 / 100 ))M
    innodb_log_buffer_size=$(( $MEMORY_LIMIT * 13 / 100 ))M
    #/ memory section
    max_connections=$(( $MEMORY_LIMIT / 512 ))
fi

export MYSQL_KEY_BUFFER_SIZE=${MYSQL_KEY_BUFFER_SIZE:-$key_buffer_size}
export MYSQL_READ_BUFFER_SIZE=${MYSQL_READ_BUFFER_SIZE:-$read_buffer_size}
export MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-$innodb_buffer_pool_size}
export MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-$innodb_log_file_size}
export MYSQL_INNODB_LOG_BUFFER_SIZE=${MYSQL_INNODB_LOG_BUFFER_SIZE:-$innodb_log_buffer_size}
export MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS:-$max_connections}
