#!/bin/bash
source cgroup-limits

export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}
export MYSQL_DATABASE=${MYSQL_DATABASE:-}
export MYSQL_USER=${MYSQL_USER:-}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-}

# Fall back to random root password
if [[ -z "$MYSQL_ROOT_PASSWORD" ]]; then
  export MYSQL_RANDOM_ROOT_PASSWORD="yes"
fi

# MySQL config
export MYSQL_DEFAULTS_FILE=${MYSQL_DEFAULTS_FILE:-"/opt/app-root/etc/mysqld/my.cnf"}

# MySQL Configuration
export MYSQL_MAX_ALLOWED_PACKET=${MYSQL_MAX_ALLOWED_PACKET:-200M}
export MYSQL_TABLE_OPEN_CACHE=${MYSQL_TABLE_OPEN_CACHE:-2000}

export MYSQL_LOWER_CASE_TABLE_NAMES=${MYSQL_LOWER_CASE_TABLE_NAMES:-0}
export MYSQL_FT_MIN_WORD_LEN=${MYSQL_FT_MIN_WORD_LEN:-4}
export MYSQL_FT_MAX_WORD_LEN=${MYSQL_FT_MAX_WORD_LEN:-20}

# Auto-tuning
if [ -z "${MEMORY_LIMIT:-}" ]; then
  # Safe defaults
  innodb_buffer_pool_size='32M'
  innodb_log_file_size='8M'
  innodb_log_buffer_size='8M'

  thread_concurrency='2'
  max_connections='16'
else
  innodb_buffer_pool_size=$(( $MEMORY_LIMIT * 50 / 100 ))M

  if [ $MEMORY_LIMIT -gt 4096 ]; then
    innodb_log_file_size='128M'
    innodb_log_buffer_size='128M'
  elif [ $MEMORY_LIMIT -gt 2048 ]; then
    innodb_log_file_size='64M'
    innodb_log_buffer_size='64M'
  elif [ $MEMORY_LIMIT -gt 512 ]; then
    innodb_log_file_size='32M'
    innodb_log_buffer_size='32M'
  else
    innodb_log_file_size='8M'
    innodb_log_buffer_size='8M'
  fi

  thread_concurrency=$((CPU_CORES * 2))

  # 16 max connections per 512MB
  max_connections=$(( $MEMORY_LIMIT / 512 * 16 ))
  [[ $max_connections -le 16 ]] && max_connections=16
  [[ $max_connections -gt 256 ]] && max_connections=256
fi

export MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-$innodb_buffer_pool_size}
export MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-$innodb_log_file_size}
export MYSQL_INNODB_LOG_BUFFER_SIZE=${MYSQL_INNODB_LOG_BUFFER_SIZE:-$innodb_log_buffer_size}
export MYSQL_THREAD_COCURRENCY=${MYSQL_THREAD_COCURRENCY:-$thread_concurrency}
export MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS:-$max_connections}
